export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PLAYERS = "FILTER_PLAYERS";
export const LOAD_PLAYERS = "LOAD_PLAYERS";
export const GET_PLAYERS_BEGIN = "GET_PLAYERS_BEGIN";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_ERROR = "GET_PLAYERS_ERROR";
